osqp/osqp-python

- setup.py
`find_package(PythonLibs ${PYTHON_VER_NUM})` failed if python is not installed in standard location. this patch fixes that
> provide python include and libs folders to cmake

- extension/include/osqpobjectpy.h
- module/tests/non_convex_test.py
- modulepurepy/_osqp.py
- Made some edits in the `osqpobjectpy.h` file in order to handle `NaN` in the objective value when the solver status value is `OSQP_NON_CVX`.
- Made some edits in pure Python implementation to match the C one.
- Added a unit test when the problem is non-convex.
> Added OSQP_NON_CVX flag

- module/tests/dual_infeasibility_test.py
- module/tests/primal_infeasibility_test.py
This is a Python example of an infeasible problem from https://github.com/oxfordcontrol/osqp/issues/144
Download [data.zip](https://github.com/oxfordcontrol/osqp-python/files/3212803/data.zip) and run:
```python
import osqp
import numpy as np
from scipy import sparse
import zipfile
with zipfile.ZipFile('./data.zip', 'r') as zip_ref:
zip_ref.extractall('./')
P = sparse.load_npz("data_P.npz")
A = sparse.load_npz("data_A.npz")
vec = np.load("data_vec.npz")
q = vec['q']
l = vec['l']
u = vec['u']
prob = osqp.OSQP()
prob.setup(P, q, A, l, u)
res = prob.solve()
```
> Fix primal infeasibility check

- module/codegen/code_generator.py
When running the example posted in https://github.com/oxfordcontrol/osqp/issues/177, I got the following CMake error:
```
Getting workspace from OSQP object...                           [done]
Creating target directories...                                  [done]
Copying OSQP sources...                                         [done]
Generating customized code...                                   [done]
Compiling Python wrapper...                                     CMake Error at CMakeLists.txt:120 (add_subdirectory):
The source directory
C:/Users/goran/Documents/code/python/osqp-python/code/include
does not contain a CMakeLists.txt file.
```
This should be fixed with this PR.
> Fixed a typo in codegen

- module/codegen/code_generator.py
- module/utils.py
Otherwise, it throws `NameError: name 'warn' is not defined`.
> Include warning package

- requirements.txt
See [issue 34](https://github.com/oxfordcontrol/osqp-python/issues/34) by @wkschwartz
> fix(requirements): install future only if python version <= 2.7

- pyproject.toml
Set the `cibuildwheel` python version to `cp-3*` to allow building wheels on Python `3.10` and beyond.
> building wheels on cp3*

- pyproject.toml
It is best practice to build against the oldest version of Numpy a package can work with, as binaries compiled with old Numpy versions are binary compatible with newer Numpy versions, but not vice versa.
With ecos2.0.8 I'm experiencing the same as for example displayed in cvxpy/cvxpy#1367.
See https://pypi.org/project/oldest-supported-numpy/ for more details
Same PR as for ecos: https://github.com/embotech/ecos-python/pull/37
> use oldest supported numpy

- src/osqp/codegen/code_generator.py
- src/osqp/interface.py
Users might want to generate code without compiling the python extension. One such case is when `OSQP` codegen is used within `CVXPY` codegen, and the `CVXPY` python extension is used for prototyping. 
This PR introduces the argument `compile_python_ext` for the `codegen` methods. If `True` (default), the python extension is compiled. If `False`, all files related to the python extension are still rendered and the `CMake` project is still created. This way, advanced users can still compile the python extension by hand, for example by:
```bash
cd dir_name/src
python setup.py --quiet build_ext --inplace
```
> New 'compile_python_ext' argument for codegen.

- src/osqp/codegen/utils.py
In the case of linear programs, the `csc` matrix `P` is empty. Previously, amongst others, empty (zero length) index and data arrays for `P` were generated. Some compilers will throw an error because of this. This pull request prevents the declaration of empty arrays and specifies `NULL` pointers where needed.
> Preventing empty array declarations during code generation.

- .github/workflows/build.yml
Added linux aarch64 wheel support.
Related to #53. @bstellato Could you please review this PR..
> Add linux aarch64 wheel support

- src/bindings.cpp.in
- src/osqp/interface.py
Making use of newly exposed osqp_set_default_codegen_defines API function; minor moving around of binding functions
> Setting default OSQPCodegenDefines through function

- pyproject.toml
SciPy 1.13 fixed the sparse matrix ordering problem we had with the tests, so we can now use that.
> Only exclude SciPy version 1.12

- .github/workflows/build_aarch64.yml
- .github/workflows/build_cuda.yml
- .github/workflows/build_default.yml
- .github/workflows/build_mkl.yml
- .github/workflows/pre_commit.yml
- CMakeLists.txt
- pyproject.toml
Various updates to the CI system, including:
* Build both the arm64 and x86_64 macOS wheels on GitHub actions. The macos-13 runner is x86_64 architecture, so build those wheels there. The macos-latest runner is arm64 architecture, so build those wheels there.
* Change the version string to build for all support Python versions by default.
* Update to artifacts v4 action. This requires uploading each OS' artifacts separately and then combining them in another job after the matrix is completed.
Update the workflow triggering conditions:
* No longer use a develop branch, so only run with PRs against the
master branch
* Run the pre-commit checks on all branches to flag potential errors
before a PR is made
> Update CI wheel building

- .github/workflows/build.yml
- setup.py
Add the macOS arm64 architecture to the wheel builds of the 0.6 branch. This is done similar to qdldl-python in https://github.com/osqp/qdldl-python/pull/39.
> Add macOS arm64 wheel builds for v0.6

- CMakeLists.txt
- src/bindings.cpp.in
- src/osqp/interface.py
- src/osqp/tests/derivative_test.py
python wrapper api change to account for the fact that `osqp_adjoint_derivative_compute` doesn't support a `y_l` and `y_u` anymore.
Pinning to current HEAD of `osqp` `master`.
> no dl/du in osqp_adjoint_derivative_compute anymore

- pyproject.toml
`osqp` requires python>=3.8, since codegen doesn't support it (on account of pybind11 not supporting it), and we're only testing on cibuildwheel with py>=3.8
> removed support for py<3.8,

- src/osqp/nn/torch.py
I'm not sure why the following `print` statements were put in - merely `print`ing out an error and proceeding like nothing happened doesn't accomplish anything IMO, and only hides the otherwise invaluable stack trace. It's better to fail explicitly with an `ImportError`.
I noticed this when a bad installation of `torch` in my environment was preventing an internal import deep inside pytorch (triggered in our code on `from torch.nn import Module`), but this was hard to track down because of this `print`.
If the intention here was to allow `osqp` code execution even in the absence of the `torch` module, that's understandable, but again, no other code in `osqp` seems to be inadvertently picking up this module where it shouldn't except a unit test, and doing an `from osqp.nn.torch import ..` …
> failing as we should, instead of printing out an error

- .github/workflows/build_cuda.yml
- .github/workflows/build_default.yml
- .github/workflows/build_mkl.yml
3.13 is in RC still, and not all dependencies have wheels for it built yet.
This should fix the issues we see in https://github.com/osqp/osqp-python/pull/155, since cibuildwheel 2.20 added Python 3.13.
> Temporarily skip building wheels for 3.13 until it is released

- examples/basic_usage.py
- examples/exception_handling.py
- src/bindings.cpp.in
- src/osqp/__init__.py
- src/osqp/interface.py
- src/osqp/nn/torch.py
- src/osqp/tests/derivative_test.py
- src/osqp/tests/non_convex_test.py
I'm calling the enum `SolverStatus` since I understand there are other status values possible (during setup etc), but we can use `Status` if you think it won't be an issue in the future.
A typical usage would be:
```
res = prob.solve()
assert res.info.status_val == osqp.SolverStatus.OSQP_SOLVED
```
I'm still letting access to these status values to go through result -> info instead of through the solver directly, to maintain the "thin" in the thin python wrapper.
> Introduced an osqp.SolverStatus enum
